librarian_list = [
    {"name": "Linda Clement", "title": "Faculty Librarian", "campus": ["Cypress Creek"]},
    {"name": "Barbara Jorge", "title": "Faculty Librarian", "campus": ["Hays"]},
    {"name": "Martha Clark", "title": "Faculty Librarian", "campus": ["Eastview", "Highland"]},
    {"name": "Betsy Young", "title": "Faculty Librarian", "campus": ["Highland", "Northridge"]},
    {"name": "Maria Ruelas", "title": "Faculty Librarian", "campus": ["Northridge"]},
    {"name": "Jeremy Donald", "title": "Faculty Librarian", "campus": ["Highland", "Northridge"]},
    {"name": "Terry Barksdale", "title": "Faculty Librarian", "campus": ["San Gabriel"]},
    {"name": "Lynda Infante Huerta", "title": "Faculty Librarian", "campus": ["Riverside"]},
    {"name": "Jorge Lopez-McKnight", "title": "Faculty Librarian", "campus": ["Riverside"]},
    {"name": "Steve Self", "title": "Faculty Librarian", "campus": ["Eastview"]},
    {"name": "Ryan Slattery", "title": "Faculty Librarian", "campus": ["Round Rock"]},
    {"name": "Adrian Graham", "title": "Faculty Librarian", "campus": ["South Austin"]},
    {"name": "Jonathan Buckstead", "title": "Faculty Librarian", "campus": ["Cypress Creek"]},
    {"name": "Jordan Hagan", "title": "Faculty Librarian", "campus": ["Rio Grande"]},
    {"name": "Dave Wilson", "title": "Faculty Librarian", "campus": ["Rio Grande"]},
    {"name": "Kara Dixon", "title": "Faculty Librarian", "campus": ["Hays", "South Austin"]},
    {"name": "Molly Ledbetter", "title": "Faculty Librarian", "campus": ["Cypress Creek", "San Gabriel"]},
    {"name": "Jesse Saunders", "title": "Faculty Librarian", "campus": ["Round Rock"]},
    {"name": "Alexander Speetzen", "title": "Faculty Librarian", "campus": ["Highland"]},
    {"name": "Mavis Klemcke", "title": "Faculty Librarian", "campus": ["South Austin"]},
    {"name": "Cassidy Reid", "title": "Faculty Librarian", "campus": ["Elgin"]},
    {"name": "Rosalind Clifford", "title": "Faculty Librarian", "campus": ["Highland"]},
    {"name": "James Loomis", "title": "Faculty Librarian", "campus": ["Riverside", "High Schools - In-Person"]},
    {"name": "Mary Havens", "title": "Faculty Librarian", "campus": ["Elgin", "High Schools - In-Person"]},
    {"name": "Kristyn Pittman", "title": "Faculty Librarian", "campus": ["Round Rock", "San Gabriel", "High Schools - In-Person"]},
    {"name": "Julie Brooks", "title": "Hourly Instructional Librarian", "campus": []},
    {"name": "Sara Ganderia-Escamilla", "title": "Hourly Instructional Librarian", "campus": ["Eastview", "Elgin", "Highland", "Rio Grande", "San Gabriel"]},
    {"name": "Vanessa Wilson", "title": "Hourly Instructional Librarian", "campus": ["Hays", "Riverside", "South Austin"]},
    {"name": "Wendy Thompson", "title": "Hourly Instructional Librarian", "campus": ["Northridge"]},
    {"name": "Andrea Heckler", "title": "Head Librarian", "campus": ["San Gabriel"]},
    {"name": "Christine Mook", "title": "Head Librarian", "campus": ["Round Rock"]},
    {"name": "Courtney Mlinar", "title": "Head Librarian", "campus": ["Elgin", "Round Rock", "South Austin"]},
    {"name": "Deborah Sellars", "title": "Head Librarian", "campus": ["Highland", "Rio Grande"]},
    {"name": "Jennifer Weber", "title": "Head Librarian", "campus": ["Northridge"]},
    {"name": "Lola Cowling Watters", "title": "Head Librarian", "campus": ["Hays"]},
    {"name": "Pamela Carlile", "title": "Head Librarian", "campus": ["Riverside"]},
    {"name": "Renee Kuhles", "title": "Head Librarian", "campus": ["Eastview", "Highland"]},
    {"name": "Teri Rogers", "title": "Head Librarian", "campus": ["Cypress Creek"]},
    {"name": "Toyya Cisneros", "title": "Head Librarian", "campus": ["South Austin"]},
    {"name": "Jon Luckstead", "title": "Faculty Librarian", "campus": ["Highland"]}
]